apiVresion: apps/v1
kind: Deployment
metadata:
 name: petclininc-deployment
 labels:
  app: pet
spec:
 replicas: 2
 selector:
  matchLabels:
   app: pet
 template:
  metadata:
   name: petclinic-pod
   labels:
    app: pet
  spec:
   containers:
    - name: petclinic-containers
      image: devopsproject2.azurecr.io/petclinic:latest
      ports:
	   - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
 name: petclinic-service
spec:
 type: ClusterIP
 ports:
 - targetPort: 8080
   port: 80
 selector:
  app: pet